# Generated by Django 3.2.7 on 2021-10-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_places_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=models.TextField(unique=True),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('title', 'description_short', 'description_long'), name='unique_places'),
        ),
    ]
