# Generated by Django 3.2.7 on 2021-10-05 10:22

from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20211005_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=pathlib.PureWindowsPath('C:/Users/garanzha/OneDrive/Рабочий стол/dvmn/media'))),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
        ),
    ]
