# Generated by Django 3.2.7 on 2021-10-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='priority',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
