# Generated by Django 3.2.7 on 2021-10-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_image_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='priority',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
