# Generated by Django 3.2.7 on 2021-10-05 19:42

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_image_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('C:/Desktop/sandbox/Devman/Django_Task_1/media')),
        ),
    ]
