# Generated by Django 3.2.7 on 2021-10-09 14:26

from django.db import migrations, models
import places.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_description_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=places.models.Image.get_upload_path),
        ),
    ]
