# Generated by Django 3.2.7 on 2021-10-10 15:31

from django.db import migrations, models
import places.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20211009_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('priority',), 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('title',), 'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=places.models.Image.get_upload_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.CharField(max_length=300, unique=True, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название локации'),
        ),
    ]
