# Generated by Django 3.2.7 on 2021-10-17 22:08

from django.db import migrations, models
import places.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_auto_20211013_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to=places.models.get_upload_path, verbose_name='Изображение'),
        ),
    ]
