# Generated by Django 3.2.7 on 2021-10-17 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='location',
            new_name='place',
        ),
    ]
