# Generated by Django 3.2.7 on 2021-10-23 06:51

from django.db import migrations, models
import places.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_alter_image_place'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='place',
            name='unique_places',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(unique=True, upload_to=places.models.get_upload_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название локации'),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('title', 'longitude', 'latitude'), name='unique_places'),
        ),
    ]
