# Generated by Django 3.2.7 on 2021-10-23 07:08

from django.db import migrations, models
import places.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_auto_20211023_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=places.models.get_upload_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='priority',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
