# Generated by Django 3.2.7 on 2021-10-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_place_pub_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='place',
            name='unique_places',
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='place',
            name='pub_status',
            field=models.CharField(choices=[('D', 'Черновик'), ('P', 'Опубликован')], db_index=True, default='D', max_length=1, verbose_name='Статус публикации'),
        ),
    ]
