# Generated by Django 3.2.7 on 2021-10-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0019_auto_20211024_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
    ]
